services:
  # MongoDB Service
  mongo_db:
    container_name: Notes-Backend-MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ayaandey2002  # Username
      MONGO_INITDB_ROOT_PASSWORD: 1234   # Password

volumes:
  mongo_data: